
export const supabaseUrl = 'https://ssdofagddakowthmuawd.supabase.co';

export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzZG9mYWdkZGFrb3d0aG11YXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA4OTQ0MTgsImV4cCI6MjA0NjQ3MDQxOH0.lnYiGvYcpo4r5abD4GZ0Znba80LQi-_4tRJvzdfdGos';